name: lessonpre-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip
  - openssl=3.6.0
  - libffi=3.5.2
  - libcurl=8.17.0
  - zstd=1.5.7
  - poppler=25.12.0
  - libpng=1.6.53
  - libjpeg-turbo=3.1.2
  - cairo=1.18.4
  - freetype=2.14.1
  - pip:
    - # 建议在重新安装环境后使用 pip install -r requirements.txt 安装其余包
